### ISSUE TITLE
[BUG] - Crash installing a game on steam

### ISSUE THREAD

**Issue by Corgipolloo** [Atlas-OS/Atlas#1148] opened 2024-07-15 00:31 UTC
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

When I install a game on Steam, it shows me a blue screen, it crashes and I have to restart Windows, this only happens to me on Steam, when I install any game and my PC crashes out of nowhere, this only happened after the Ame Wizard

### Steps to reproduce

i cant take a screenshot bcause it will crash windows, only startup steam and 30 seconds later it crashes, with the error whea_uncorrectable_error on the blue screen

### Expected behavior

i expected to install my game normally and crashes into a blue window

### Actual behavior

installa a game on steam after the ame wizard beta and blue screen appears

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

![Screenshot_1](https://github.com/user-attachments/assets/8206ec24-3464-4f4a-9040-d089b52e0544)
the ram is ddr4, 3200 mhz 
2 ssd of 1 tb each one
and the driver of the 3070ti is the one that installed windows

### Additional content

i think it might be the part of installing something on steam

**Comment by scanash00** [comment] 2024-07-15 00:42
Hey there! My first question is, did you reinstall windows (With a clean windows install) before installing Atlas? If you did, did you install your Drivers? Please let me know so i can help any further!

**Comment by Corgipolloo** [comment] 2024-07-15 01:11
yeah, a clean install, a new windows on you web, and the drivers with nv

**Comment by scanash00** [comment] 2024-07-15 01:16
Did you install the drivers for your AMD CPU?

**Comment by Ast3risk-ops** [comment] 2024-07-15 01:16
btw @Corgipolloo did you know if you take your phone, open the camera, point it at the screen and take a picture you can do a screenshot of anything?

**Comment by Corgipolloo** [comment] 2024-07-15 01:39
https://github.com/user-attachments/assets/7dec5324-dacb-4f73-a539-54ac441c96e9
https://github.com/user-attachments/assets/dcd8c145-72c9-4a40-8315-eaceaa5c0450

**Comment by Corgipolloo** [comment] 2024-07-15 01:41
> Did you install the drivers for your AMD CPU?

yeah

**Comment by scanash00** [comment] 2024-07-15 02:05
A "WHEA_UNCORRECTABLE_ERROR" BSOD is typically related to hardware issues, and it can be caused by various factors such as failing hardware components, driver problems, and software conflicts. The error message indicates that a hardware error has occurred that the Windows operating system cannot recover from.

**Comment by scanash00** [comment] 2024-07-15 02:07
Try adjusting this:
- Check if your system clock is synced
- Run DISM and SFC
- Try Reinstalling the Drivers and run Windows Update.

**Comment by JayXTQ** [comment] 2024-07-15 07:26
As we've worked out this isn't an Atlas issue, I will be closing this.

**Closed by JayXTQ** 2024-07-15 07:26 UTC
Labels: bug
