### ISSUE TITLE
[BUG REPORT] - Wired headphones and external speakers not detected until laptop is restarted

### ISSUE THREAD

**Issue by ashjaylk** [Atlas-OS/Atlas#844] opened 2023-07-08 13:17 UTC
### Description

I'm facing an issue where my wired headphones are not being recognized by the system when I connect them to my laptop. The device is not listed in the Device Manager or Windows audio settings. However, when I restart my laptop, the headphones are detected and work properly. The same issue occurs when connecting external speakers, requiring a reboot to make them functional.

### Steps to reproduce

1. Connect wired headphones or external speakers with a 3.5 mm jack to the laptop.
2. Observe that the device is not detected in the Device Manager or Windows audio settings.
3. Reboot and check again

### Expected behavior

Wired headphones and external speakers should be recognized and listed as audio output devices upon connecting them to the laptop.

### Actual behavior

Wired headphones and external speakers are not detected by the system until a restart is performed.

### Atlas Version

Atlas 10 22H2

### Desktop information

Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz 1.19 GHz
8GB RAM
Intel GPU

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

- The internal audio system of the laptop is functioning correctly
- Interestingly, the 3.5 mm port works flawlessly in the Linux dual-boot environment, suggesting the problem is specific to AtlasOS.
- I have installed the latest OEM drivers from Dell for the audio system, ensuring they are up to date.
- The issue persists regardless of the specific brand or model of the headphones or external speakers used.
- Other USB devices connect and function properly without requiring a restart.

**Comment by Swanndolia** [comment] 2023-07-11 02:27
Going inside the sound menu and right clicking the playback device, configure speakers and finishing the process seems to fix it, while its not done you're also unable to play the test tone

**Comment by notdido** [comment] 2023-07-18 21:08
Hey, I used to have a DELL Laptop, and had very much the same issue. For me personally the problem *was not* caused by Atlas but rather shit drivers from DELL because that bug occurred for me even on stock Windows with no debloats, it appears to glitch out if Waves MaxxAudio Pro was either uninstalled/disabled from startup, the only way for the laptop to reflect the change in audio was to go into the app and change up the input type from speakers to headphones or if it was already on headphones, to speakers and back to headphones so the laptop recognizes them. **This is rather a workaround and not a fix, but after researching back then, I havent personally found a fix.**

**Comment by notdido** [comment] 2023-07-18 21:12
*Forgot to mention if you leave Waves MaxxAudio Pro on startup, headphones & external speakers detection should work correctly, its a rather shitty solution but I guess Dell cannot work without bloatware ¯\_(ツ)_/¯

**Comment by JayXTQ** [comment] 2023-08-02 19:21
Due to no comment after this, I will be closing. If mistaken for being fixed then please mention so

**Closed by JayXTQ** 2023-08-02 19:21 UTC
Labels: bug
