### ISSUE TITLE
[BUG REPORT] - DX12U is not working

### ISSUE THREAD

**Issue by GaborVarga239** [Atlas-OS/Atlas#641] opened 2023-04-01 14:01 UTC
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

when i try to enable DX12U on atlas 22h2 it says "this version of windows doesn't support directstorage IO optimization"

### Steps to reproduce (if applicable add screenshots)

1. Enable GameBar
2. Check if it supports dx12U
3. it says it doesn't

### Expected behavior

Support for DX12U

### Actual behavior (if applicable add screenshots)

It says: "This version of windows doesn't support directstorage IO optimization"

### Atlas Version (1803/20H2/21H2)

22h2

### Desktop information

AMD Ryzen 5500
16 Gb ram
1070 8gb

### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

**Comment by Xyueta** [comment] 2023-04-13 06:50
https://www.reddit.com/r/Windows10/comments/zn9ajs/any_idea_why_direct_storage_is_not_supported/

**Comment by GaborVarga239** [comment] 2023-04-13 14:42
Didn't help

**Comment by JayXTQ** [comment] 2023-04-15 16:17
I take it, DX12U was working on default **Windows 10 22H2**

**Comment by Antag0nisticWomble** [comment] 2023-04-16 11:22
DX12U still not supporting storage features in latest actions.

**Comment by Antag0nisticWomble** [comment] 2023-04-17 04:27
I've just tested this on a vanilla windows 10 installation. 
I get the same response on that too.
It reports this version of windows doesn't support Direct Storage IO optimizations.

**Comment by JayXTQ** [comment] 2023-04-20 08:22
@GaborVarga239 you haven't responded to my question, please respond otherwise issue will be closed because @Antag0nisticWomble has confirmed that the issue repeats on Windows 10 which means this is not an Atlas issue.

**Comment by GaborVarga239** [comment] 2023-04-20 17:19
It works on stock Windows 10/11

**Comment by Antag0nisticWomble** [comment] 2023-04-20 18:04
> It works on stock Windows 10/11

I tested it on a stock windows 10 installation and it said it doesn't support direct storage io optimizaitons. 
That's with a 970 pro nvme and 3060TI

**Comment by JayXTQ** [comment] 2023-04-21 13:47
Hm, this seems like more of an issue on your side @GaborVarga239 rather than Atlas. Do some research and if you get a solution, comment it below but for the reason that this is a issue on your side I will be closing this. Have a great day!

**Closed by JayXTQ** 2023-04-21 13:47 UTC
Labels: bug
