### ISSUE TITLE
After running atlas-config.cmd, the explorer loads very slowly

### ISSUE THREAD

**Issue by SuXiChao1101** [Atlas-OS/Atlas#580] opened 2023-02-16 10:44 UTC
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

I particularly admire the optimisation capabilities of the Atlas script, but I wanted to run the script independently to optimise my computer. I downloaded atlas-config.cmd and removed the "argumentFAIL" section and atlas-config.cmd worked fine. After running it and restarting the computer, I noticed that when some programs called explorer to open a file, the explorer window would become very laggy. For example, if I use a Chromium browser, when I upload some files, the browser will call explorer and when Chromium calls explorer to open the file, the explorer window will become very laggy and it will take about 30 seconds to return to normal.
I don't know if there is a link between this and my installation of StartAllBack.
The system environment is Win11 and the kernel version number is 22000.1335
This article is translated using DeepL and may have some grammatical problems, so please understand, thank you!

### Steps to reproduce (if applicable add screenshots)

1.Download atlas-config.cmd
2.Delete "argumentFAIL" related content
3.Restart the computer

### Expected behavior

Services are optimised and common system components are functioning properly

### Actual behavior (if applicable add screenshots)

Some scenarios where explorer is called to open a file (e.g. Chromium browser will call explorer to open a file), explorer will become very laggy

### Atlas Version (1803/20H2/21H2)

atlas-config.cmd downloaded on 11 February 2023

### Desktop information

Win11 x64,22000.1335
StartAllBack is installed

**Comment by PencilNavigator** [comment] 2023-02-16 10:56
Duplicate of https://github.com/Atlas-OS/Atlas/issues/572

**Closed** 2023-02-16 10:57 UTC
Labels: invalid
