### ISSUE TITLE
[BUG REPORT] - Can't use Xbox One controller with bluetooth

### ISSUE THREAD

**Issue by GaborVarga239** [Atlas-OS/Atlas#623] opened 2023-03-29 09:09 UTC
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

Hi!

I have an issue where i connect my Xbox One controller with bluetooth to my Atlas pc, the controller connects, but it  just doesn't works.

### Steps to reproduce (if applicable add screenshots)

1. Connect the controller in the bluetooth settings.
2. Try to use the controller

### Expected behavior

Windows should open gamebar if i press the xbox button, games should work with the controller

### Actual behavior (if applicable add screenshots)

Atlas doesnt respond to anything that i press on the controller (gamebar doesn't open, etc)

### Atlas Version (1803/20H2/21H2)

2009/20h2

### Desktop information

Ryzen 5500
16gb ram
GTX 1070 8gb OC

**Comment by JayXTQ** [comment] 2023-03-29 09:12
1. Did you enable bluetooth in the atlas settings?
2. Did you install bluetooth drivers
3. Did you enable gamebar and fso?

**Comment by GaborVarga239** [comment] 2023-03-29 09:16
1. I did enable bluetooth.
2. I installed the drivers
3. Yes i did, it works fine with Win+G

**Comment by JayXTQ** [comment] 2023-03-29 09:20
Ok, I take it this worked fine in normal Windows 10?

**Comment by GaborVarga239** [comment] 2023-03-29 09:21
It worked fine in normal Windows 10 and 11

**Comment by GhoulBoii** [comment] 2023-03-29 10:06
Go to [Gamepad tester](https://gamepad-tester.com/) and see if your controller is showing up or not.

**Comment by GaborVarga239** [comment] 2023-03-29 12:26
I tested it, it works fine on the website.
It also works with atlas if i use a cable.

**Comment by PencilNavigator** [comment] 2023-04-01 18:07
please try 22H2 see if it fixes this problem.

**Comment by GaborVarga239** [comment] 2023-04-02 10:28
It didn't fix


PencilNavigator ***@***.***> ezt írta (időpont: 2023. ápr.
1., Szo, 20:08):

**Comment by GaborVarga239** [comment] 2023-04-02 15:38
Now the controller can't even connect to the pc

**Comment by PencilNavigator** [comment] 2023-04-02 16:11
will be looking into it.

**Comment by Antag0nisticWomble** [comment] 2023-04-02 17:50
![Untitled](https://user-images.githubusercontent.com/53240891/229370030-9ba0c23c-d1c3-4b47-ade3-6f4a482d10cf.png)
Make sure you have the shortcut turned on by default it is off.

**Comment by JayXTQ** [comment] 2023-04-02 20:21
@GaborVarga239 maybe this works for you?

**Comment by GhoulBoii** [comment] 2023-04-07 11:03
Have you installed your bluetooth drivers? I am on Atlas 22H2 and I can confirm that after installing my bluetooh drivers and connecting my xbox one s controller wirelessly, I am able to use it in games and it also gets detected correctly on gamepad-tester.

**Comment by GaborVarga239** [comment] 2023-04-11 15:13
As i said, there are no drivers for it. Because its plug&play. the name is csr8510A10

**Comment by GaborVarga239** [comment] 2023-04-12 12:36
disabling, and enabling bluetooth again in the atlas folder fixed it

**Comment by Xyueta** [comment] 2023-04-15 08:47
Possibly re solved in https://github.com/Atlas-OS/Atlas/commit/e5a67a343fccd46fba67877129181708aa48df08.

**Comment by JayXTQ** [comment] 2023-04-15 16:19
Can someone test if this is fixed in the dev builds made (GitHub Actions)

**Comment by Antag0nisticWomble** [comment] 2023-04-16 11:22
Working fine in original release and latest actions.

**Comment by JayXTQ** [comment] 2023-04-16 11:31
> Working fine in original release and latest actions.

Do you have that specific controller though? @Antag0nisticWomble because that was the issue not just any controller.

**Comment by Antag0nisticWomble** [comment] 2023-04-16 11:33
> 

Xbox Wireless controller.
Yes works fine.

**Comment by JayXTQ** [comment] 2023-04-16 11:34
No. The **Xbox One** controller, each controller has some different technology in them afaik.

**Comment by JayXTQ** [comment] 2023-04-16 11:34
When I say Xbox One btw I mean the original Xbox One

**Comment by Antag0nisticWomble** [comment] 2023-04-16 11:37
It's not atlas that's the issue. It's your bluetooth drivers.
I had the same issue originally where I couldn't connect bluetooth devices.
After using the enable bluetooth script and finding the drivers for my device everything worked fine.

**Comment by JayXTQ** [comment] 2023-04-16 11:40
Problem is, the Xbox One controller doesn’t have bluetooth, it has it’s own wireless technology which requires the dongle. Opening issue again as you don’t have the right controller it seems.

**Comment by Xyueta** [comment] 2023-04-16 16:22
tested, works for me, if the issue is present for anybody else, please open back again.

**Closed by Xyueta** 2023-04-16 16:22 UTC
Labels: bug, low priority

**Comment by JayXTQ** [comment] 2023-04-16 16:39
> tested, works for me, if the issue is present for anybody else, please open back again.

For the original Xbox One controller that requires the dongle?

**Comment by Xyueta** [comment] 2023-04-16 16:40
I used the xbox controller using Bluetooth, as the issues is related to it.

**Comment by JayXTQ** [comment] 2023-04-16 16:43
Oh yeah totally forgot about what this issue was about, thought it meant the xbox controller that required the dongle. My bad.

**Comment by GaborVarga239** [comment] 2023-04-20 17:21
@Antag0nisticWomble As I said, there are no drivers for it, its plug&play

**Comment by Antag0nisticWomble** [comment] 2023-04-20 18:06
Default drivers are available through microsoft update packages if you're having issues.
But you need to run the bluetooth enable script and if that doesn't work you need to google your bluetooth devices HWID to get the driver.

**Comment by GaborVarga239** [comment] 2023-04-22 14:17
As i said the bluetooth script was enabled, then disabled it restarted, enabled it again, restarted and it worked. And as i said a couple of times here: There. Are. No. Drivers. For. The. Bluetooth. Adapter. It. Is. Plug. And. Play. The. Vendor. Didnt. Upload. Any. Drivers. For. This. Model.

**Comment by GaborVarga239** [comment] 2023-08-04 13:19
Changed dongles, the issue still persists
