### ISSUE TITLE
[BUG REPORT] - MS Office close when try to save

### ISSUE THREAD

**Issue by PencilNavigator** [Atlas-OS/Atlas#653] opened 2023-04-04 08:41 UTC
### Description

App will immediatelt quit after clicking "save" button in MS Office.

### Steps to reproduce (if applicable add screenshots)

using word as an example
1. make a new .docx file
2. open with MS Office Word
3. add random stuff in doc and save
4. word quits.

### Expected behavior

Saved properly and works.

### Actual behavior (if applicable add screenshots)

it was not saved properly.

### Atlas Version

Atlas 10 22H2

### Desktop information

NOT APPLICAPLE

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.com/invite/atlasos).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Additional content

(Valid issue reported on forums)
https://forum.atlasos.net/d/261-office-applications-close-when-trying-to-save

**Comment by 1nikolas** [comment] 2023-04-08 19:37
I can confirm, office apps crash when trying to save/browse etc

**Comment by kamil9650** [comment] 2023-04-09 10:31
Microsoft Office in everyone I think works like this.
Let's hope for a quick fix to this bug, because it's impossible to work. The only way goes to do, but, for example, export to another format also closes automatically or errors indicate.

**Comment by Xyueta** [comment] 2023-04-13 06:51
Possibly https://github.com/Atlas-OS/Atlas/commit/9de447449f079f0288fdf8b3d8047caff7c7194f.

**Comment by bandinfinite** [comment] 2023-04-13 13:53
yeah i too get quitted... (office 2021 pro plus activated geniunely)

**Comment by bandinfinite** [comment] 2023-04-14 03:01
@Xyueta bro I updated the office and the error was gone . (office 2021 pro plus) (also it is not pirated, i bought a key)

**Comment by a1-skeng** [comment] 2023-04-23 15:46
Trying to use a genuine 365 account browsing my local files completely crashes any office app. Commenting for awareness and to come back to see if there is a fix

**Comment by notmerca** [comment] 2023-04-26 01:14
i can confirm that office is not working in the latest Atlas, crashes when trying to save.
if this issue is closed, is there a fix? can you please comment how to apply it?
thank you

**Comment by notmerca** [comment] 2023-04-26 15:34
Additional information: I also tried replacing office 365 with an activated Office 2021
Unfortunately, this doesn't solve the issue

**Comment by JayXTQ** [comment] 2023-04-27 09:00
So this still persists on https://github.com/Atlas-OS/Atlas/releases/latest ?

**Comment by Xyueta** [comment] 2023-04-27 09:02
Not good, will be checked later.

**Comment by gdnzz** [comment] 2023-04-27 09:02
I can also confirm I have seen some people reporting the same thing on discord

**Comment by Mamu1985** [comment] 2023-04-30 06:10
Got the same issue office 365 on Atlas 22H2. Browsing causes excel or word to crash.

**Comment by JayXTQ** [comment] 2023-05-02 07:25
Good news, will be fixed in v0.3.0

**Closed by JayXTQ** 2023-05-02 07:25 UTC
Labels: bug, high priority

**Comment by Eliseonop** [comment] 2023-05-04 04:03
Hello, the problem persists, did you find a way to solve it?

**Comment by JayXTQ** [comment] 2023-05-04 05:29
If you look at the comment above, you can assume the answer to your question.

**Comment by Kise31** [comment] 2023-06-02 00:54
does the problem still exist?

**Comment by PencilNavigator** [comment] 2023-06-02 05:12
@Kise31 If you look at the comment above, you can assume the answer to your question.

**Comment by AltahanRauf** [comment] 2023-08-13 02:16
Whats the alternative option we can use to save those files , I am having problem with Power point MS Office 365.

**Comment by sabaasa** [comment] 2023-08-13 06:30
> Whats the alternative option we can use to save those files , I am having problem with Power point MS Office 365.

none, atlas 0.2 breaks office saving, 0.3 is fixed and the 0.3 update will be releasing in one week or two with new features, bugfixes and etc.
