### ISSUE TITLE
[BUG] - Intel CPU clock speeds while gaming affected on atlasOS

### ISSUE THREAD

**Issue by crackedpotato007** [Atlas-OS/Atlas#1080] opened 2024-04-16 12:12 UTC
### Description

Booting up games like GTA5, Force the CPU down to 1100-1500MHZ instead of the usual 3000+, Turbo boost depends on temperature and monitoring that gives a sub 60 reading i.e 55-58C, as soon as the game is exited the CPU shoots back upto 3.5GHZ indicating thermal throttling wasn't the issue, GTA 5 isn't very demanding and runs comfortably on older PCs with worse specs. Running the same game in the same area with the same settings on vanilla windows 11 has the CPU consistently at 3.5+ compared to a sub 1.5 on atlas with higher temperatures indicating again they weren't a issue along with TDP draw. 

Not even considering boosting, the CPU doesn't even reach base clock

### Steps to reproduce

1. Launch a game with monitoring enabled

### Expected behavior

CPU to sit at 3ish GHZ

### Actual behavior

CPU underclocks to 1.5

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

- I3-10110U
- GPU UHD 630
- RAM 4GB DDR4
- INTEL 512GB INTEL OPTANE M.2 SSD

### Additional content

ALthough the boosting "should" be temporary the laptop almost always sits at 3+ GHz.

CPU doesn't even reach its baseclock of 2.5 and is stuck at 1.5 on game launch, similar problem observed on other games like ARMA3 aswell.

**Comment by trolljoe** [comment] 2024-04-16 21:01
did you enable power saving? can't reproduce this, maybe check powerplan too?

**Comment by he3als** [comment] 2024-04-17 12:33
Can you enable power-saving in the Atlas folder and see if it happens? If it doesn’t, then try using the High Performance power plan and see if it happens then.

**Comment by crackedpotato007** [comment] 2024-04-17 14:51
> did you enable power saving? can't reproduce this, maybe check powerplan too?

No, best performance mode is the default which i have selected, @he3als

**Comment by crackedpotato007** [comment] 2024-04-17 14:51
the cpu returns to base clock/boost right after the game is closed though

**Comment by he3als** [comment] 2024-05-27 15:18
If there's any more information about this, then feel free to respond under this comment. However, as it's not reproducible, and I can't see how it'd be related to Atlas, I'm going to have to close the issue.

Here are some things you can try:

- Installing drivers
	- If you can't find them, use Windows Update drivers
- Resetting BIOS settings
- Testing different power plans
- Enabling power saving in the Atlas folder

**Closed by he3als** 2024-05-27 15:18 UTC
Labels: bug, can't reproduce
