### ISSUE TITLE
Feature request（Language Switching）

### ISSUE THREAD

**Issue by yizg20** [Atlas-OS/Atlas#371] opened 2022-12-06 16:34 UTC
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Is your feature request related to a problem? Please describe.

I tried to switch the language in the system settings and could not do it.

### Describe the solution you would like.

You can switch to any language supported by Windows.

### Describe alternatives you have considered.

NO

### Additional context.

No

**Comment by PencilNavigator** [comment] 2022-12-06 17:35
duplicate of https://github.com/Atlas-OS/Atlas/issues/319

**Closed** 2022-12-06 17:40 UTC
Labels: enhancement

**Comment by yizg20** [comment] 2022-12-06 18:08
I used this method and a lot of content was not displayed properly.
![Cannot be displayed properly](https://user-images.githubusercontent.com/40365161/205988440-5356ce93-c6fc-4588-b818-ca7fcc10671c.png)

**Comment by uncognic** [comment] 2022-12-06 20:32
You could build your own Atlas ISO with NTLite with Chinese language and IME

**Comment by uncognic** [comment] 2022-12-06 20:33
That's the only fix I know yet to get chinese IME working

**Comment by yizg20** [comment] 2022-12-07 17:40
> You could build your own Atlas ISO with NTLite with Chinese language and IME

Refer to the condensed content of atlas os to modify a Windows original system?

**Comment by uncognic** [comment] 2022-12-08 12:23
See /src/

**Comment by yizg20** [comment] 2022-12-08 12:25
> See /src/

thanks

**Comment by yizg20** [comment] 2022-12-08 12:25
> See /src/

thanks
