### ISSUE TITLE
[BUG REPORT] - Inaccessible boot device after successful application of runbook W1022H2.0.2.apbx

### ISSUE THREAD

**Issue by Karl-WE** [Atlas-OS/Atlas#818] opened 2023-06-03 10:26 UTC
### Description

I have evaluated AtlasOS in a Hyper-V VM but it does not seem to work. This is likely because you disable Hyper-V by default and it needs to be enabled manually before rebooting the system after the wizard succeeded.

### Steps to reproduce (add screenshots if applicable)

1. deploy Windows 10 22H2 Hyper-V VM without internet connection
2. attach a secondary vhdx with 4 gb size
3. deploy atlas as per docs
4. run atlas 
5. disable security and run prereq 
6. restart vm (does so fine)
7. proceed with the wizard and runbook
8. wizard completes
9. vm restarts
10. issue happens

### Expected behavior

the runbook should detect if hyper-v is enabled or it is a hyper-v vm and ask if it should be disabled (same as you did with cpu mitigations.

### Actual behavior (add screenshots if applicable)

![image](https://github.com/Atlas-OS/Atlas/assets/45657752/c2271321-b316-4c17-8b6d-43633cb7ae9f)

### Atlas Version

Atlas 10 22H2

### Desktop information

intel i5 11600k (2 vCores Core for the VM)
64 GB (8 GB static virtual RAM for the VM)
- Samsung 970 Evo
- RTX 3080 Ti

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

### Additional content

if this is intended behaviour, and my guessing is correct please consider converting it to a feature request in the playbook / wizard.

**Comment by the-P1neapple** [comment] 2023-06-03 11:04
Hyper-V Guest Support is not available in 0.2. It has however already been implemented in the latest actions and will be supported in the next release.

**Comment by PencilNavigator** [comment] 2023-06-04 07:02
Fixed in 0.3.0, Right now if it's really needed use the actions one.

**Comment by Karl-WE** [comment] 2023-06-04 17:19
Thank you for your quick responses. The wizard does not find an updated playbook when using Atlas.Playbook.22H2.v0.2.apbx.
As a remediation I restored the VM snapshot and ran it again disabling the autostart.

I've executed the script as admin in the configuration Hyper-V / VBS, but that just threw an error that the component store is corrupted.
Haven't checked but it 0.3.0 available in the releases so far?

**Comment by notdido** [comment] 2023-06-04 19:42
> Thank you for your quick responses. The wizard does not find an updated playbook when using Atlas.Playbook.22H2.v0.2.apbx. As a remediation I restored the VM snapshot and ran it again disabling the autostart.
> 
> I've executed the script as admin in the configuration Hyper-V / VBS, but that just threw an error that the component store is corrupted. Haven't checked but it 0.3.0 available in the releases so far?

https://github.com/Atlas-OS/Atlas/actions/runs/5109914724, latest playbook action as of this message

**Comment by GhostlyCrowd** [comment] 2023-06-05 21:56
that action has expired anyone want to attach it here?

**Comment by Karl-WE** [comment] 2023-06-06 16:32
pardon @GhostlyCrowd ?

@notdido thanks for the link, I am missing how to download this as a new playbook file. Thanks for your guidance.

**Comment by GhostlyCrowd** [comment] 2023-06-06 20:34
> pardon @GhostlyCrowd ?
> 
> @notdido thanks for the link, I am missing how to download this as a new playbook file. Thanks for your guidance.

What I meant is that action build expired, so you cannot download the playbook file it made. I was hoping you had grabbed it already and could attach it to the bug report so i could grab a copy.

**Comment by GhostlyCrowd** [comment] 2023-06-09 01:31
@PencilNavigator 

I can confirm .30 does boot on hyper-v now but the dynamic resolution and multi monitor is broken this is because of the removal of the "Microsoft remote display adapter" driver

**Comment by GhostlyCrowd** [comment] 2023-06-09 02:09
And all of the remote desktop stuff, which makes the host os unable to optimally communicate with the guest os (Atlas) like copy and paste, dynamic resolution and so forth.

**Comment by Karl-WE** [comment] 2023-06-22 09:13
Plea to Filter all drivers by Hyper-V and leave them alone.

**Comment by Xyueta** [comment] 2023-06-23 09:08
Should be now fixed.

**Closed by Xyueta** 2023-06-23 09:08 UTC
Labels: bug
