### ISSUE TITLE
[BUG REPORT] - Minor issues

### ISSUE THREAD

**Issue by adibasOnSnikkers** [Atlas-OS/Atlas#936] opened 2023-11-03 21:06 UTC
### Description:

Atlas OS installation was successful, with no errors. Surprised at the number of active processes (~48) after boot. Found a few inconsistencies, please take a look. I apologize for the quality of the photos.

### Behavior:

1. The apps, or rather the shortcuts are still there, is that ok?

![2023-11-03-22-51-12-661](https://github.com/Atlas-OS/Atlas/assets/149834612/efe638ea-a25e-473a-9d28-cc5587afaec7)

2. Options Features are also in place.

![2023-11-03-22-56-50-413](https://github.com/Atlas-OS/Atlas/assets/149834612/8c1a5631-1789-4c41-9cf3-3c39dfb6aeb9)

3. Apps like: Xbox, Xbox Live, Family(?) are also on the disk.

![2023-11-03-22-59-30-300](https://github.com/Atlas-OS/Atlas/assets/149834612/2b440c73-9fda-461d-8dcc-d32a90d03763)

4. Game Bar is disabled by default, but service is still running?

![2023-11-03-22-59-30-400](https://github.com/Atlas-OS/Atlas/assets/149834612/f125fc70-16f4-4f8d-a2c5-a23e36ef2da3)
![2023-11-03-23-01-01-008](https://github.com/Atlas-OS/Atlas/assets/149834612/e518e937-831d-4c0e-a683-67954db797ad)

5. Mismatch with documentation and default configurations.

VPN
![2023-11-03-22-59-30-100](https://github.com/Atlas-OS/Atlas/assets/149834612/8805a776-5955-43f5-adba-c8e45333fc1b)
![2023-11-03-23-05-49-232](https://github.com/Atlas-OS/Atlas/assets/149834612/b74ecf4d-28a0-4b34-89b1-c92383909409)

System Restore
![2023-11-03-23-04-54-542](https://github.com/Atlas-OS/Atlas/assets/149834612/7d2e6446-160e-4f7a-a47c-e6a5f89fec36)
![2023-11-03-23-04-54-541](https://github.com/Atlas-OS/Atlas/assets/149834612/c2418557-21c3-4113-bdc0-630ad2c94f72)

6. Error after disabling Windows Firewall, but the tweak was successfully applied.
![2023-11-03-23-12-02-094](https://github.com/Atlas-OS/Atlas/assets/149834612/5506fdd5-f252-401f-8bfd-11aafa9d5fb5)

7. Unable to apply the tweak - "New context menu". Always old, from Windows 10, even after rebooting.

8. After each reboot, a terminal popup window appears for a second with the title - "Finalize installtion".

### Atlas Version:

0.3

### Desktop Information:

Device: Laptop - Aspire VN7-791G, HDD replaced by SSD (https://www.acer.com/us-en/support/product-support/VN7-791G/NX.MTHER.003/details)
OS: Windows 11 23H2

**Comment by Trirez** [comment] 2023-11-04 03:52
Like the Legends say:
Its a feature not a bug.

**Comment by Trirez** [comment] 2023-11-04 03:52
Like the Legends say:
Its a feature not a bug.

**Comment by wozzyi** [comment] 2023-11-04 10:11
the docs is outdated, and they said xbox components are kept becuz some users need it? there should have a script for removing xbox components

**Comment by Xyueta** [comment] 2023-11-04 11:16
@adibasOnSnikkers 
Open cmd as administrator
and type:

cd "C:\Program Files\WindowsApps"
dir

and send me the output

**Comment by adibasOnSnikkers** [comment] 2023-11-04 15:20
Oh, I won't be able to show the previous output, I already reinstalled again. However, after reinstalling everything seems to work. But I should note that I didn't change the installation steps.

![image](https://github.com/Atlas-OS/Atlas/assets/149834612/06089621-cca7-4289-b0dc-93d28c9408af)

Should MicrosoftEdgeUpdate.exe still work?
The folder with Edge is also present.

![2023-11-04-17-31-25-377](https://github.com/Atlas-OS/Atlas/assets/149834612/9210191c-7979-49c4-80bf-84befc1491cc)

There are also folders with installers here, as I understand it, that have already been used. Shouldn't they be deleted?

![2023-11-04-17-27-54-413](https://github.com/Atlas-OS/Atlas/assets/149834612/6ca3cd64-4662-4958-8a20-a99c42ca97b4)
![2023-11-04-17-32-53-323](https://github.com/Atlas-OS/Atlas/assets/149834612/4de2775a-2908-4b92-85f3-ca7e88e34e5c)

The Family App is not deleted after all.
![image](https://github.com/Atlas-OS/Atlas/assets/149834612/7158771a-6b32-4fd3-9a11-ca315124bf36)


Here's the new output from cmd:

`cd "C:\Program Files\WindowsApps"
dir
`

```
 Volume in drive C has no label.
 Volume Serial Number is 6E43-9797

 Directory of C:\Program Files\WindowsApps

11/04/2023  05:47 AM    <DIR>          ..
11/04/2023  07:12 AM    <DIR>          Deleted
11/04/2023  05:49 AM    <DIR>          DeletedAllUserPackages
05/06/2022  10:24 PM    <DIR>          Merged
11/04/2023  06:55 AM    <DIR>          Microsoft.DesktopAppInstaller_1.21.2771.0_neutral_split.language-ru_8wekyb3d8bbwe11/04/2023  06:55 AM    <DIR>          Microsoft.DesktopAppInstaller_1.21.2771.0_neutral_split.scale-100_8wekyb3d8bbwe
11/04/2023  06:55 AM    <DIR>          Microsoft.DesktopAppInstaller_1.21.2771.0_x64__8wekyb3d8bbwe
11/04/2023  06:55 AM    <DIR>          Microsoft.DesktopAppInstaller_2023.1005.18.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:54 AM    <DIR>          Microsoft.GamingApp_2309.1001.3.0_neutral_split.language-ru_8wekyb3d8bbwe
11/04/2023  06:54 AM    <DIR>          Microsoft.GamingApp_2309.1001.3.0_neutral_split.scale-100_8wekyb3d8bbwe
11/04/2023  06:54 AM    <DIR>          Microsoft.GamingApp_2309.1001.3.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:54 AM    <DIR>          Microsoft.GamingApp_2309.1001.3.0_x64__8wekyb3d8bbwe
11/04/2023  06:57 AM    <DIR>          Microsoft.HEIFImageExtension_1.0.63001.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:57 AM    <DIR>          Microsoft.HEIFImageExtension_1.0.63001.0_x64__8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.HEVCVideoExtension_2.0.61931.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.HEVCVideoExtension_2.0.61931.0_x64__8wekyb3d8bbwe
11/04/2023  05:39 AM    <DIR>          Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x64__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x86__8wekyb3d8bbwe
11/04/2023  05:39 AM    <DIR>          Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x86__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.Paint_11.2309.28.0_neutral_split.language-ru_8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.Paint_11.2309.28.0_neutral_split.scale-100_8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.Paint_11.2309.28.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.Paint_11.2309.28.0_x64__8wekyb3d8bbwe
11/04/2023  06:55 AM    <DIR>          Microsoft.RawImageExtension_2.1.62561.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:55 AM    <DIR>          Microsoft.RawImageExtension_2.1.62561.0_x64__8wekyb3d8bbwe
11/04/2023  05:53 AM    <DIR>          Microsoft.SecHealthUI_1000.25873.9001.0_x64__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.Services.Store.Engagement_10.0.23012.0_x64__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.Services.Store.Engagement_10.0.23012.0_x86__8wekyb3d8bbwe
11/04/2023  06:54 AM    <DIR>          Microsoft.StorePurchaseApp_22307.1401.9.0_neutral_split.language-ru_8wekyb3d8bbwe11/04/2023  06:54 AM    <DIR>          Microsoft.StorePurchaseApp_22307.1401.9.0_neutral_split.scale-100_8wekyb3d8bbwe
11/04/2023  06:54 AM    <DIR>          Microsoft.StorePurchaseApp_22307.1401.9.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:54 AM    <DIR>          Microsoft.StorePurchaseApp_22307.1401.9.0_x64__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.UI.Xaml.2.7_7.2208.15002.0_x64__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.UI.Xaml.2.7_7.2208.15002.0_x86__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.UI.Xaml.2.8_8.2310.30001.0_x64__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.UI.Xaml.2.8_8.2310.30001.0_x86__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.VCLibs.140.00.UWPDesktop_14.0.32530.0_x64__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.VCLibs.140.00.UWPDesktop_14.0.32530.0_x86__8wekyb3d8bbwe
11/04/2023  05:44 AM    <DIR>          Microsoft.VCLibs.140.00_14.0.30704.0_x64__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.VCLibs.140.00_14.0.32530.0_x64__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.VCLibs.140.00_14.0.32530.0_x86__8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.VP9VideoExtensions_1.0.62911.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.VP9VideoExtensions_1.0.62911.0_x64__8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.WebMediaExtensions_1.0.61591.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.WebMediaExtensions_1.0.61591.0_x64__8wekyb3d8bbwe
11/04/2023  06:54 AM    <DIR>          Microsoft.WebpImageExtension_1.0.62681.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:54 AM    <DIR>          Microsoft.WebpImageExtension_1.0.62681.0_x64__8wekyb3d8bbwe
11/04/2023  06:54 AM    <DIR>          Microsoft.WindowsAppRuntime.1.1_1005.616.1651.0_x64__8wekyb3d8bbwe
11/04/2023  06:54 AM    <DIR>          Microsoft.WindowsAppRuntime.1.1_1005.616.1651.0_x86__8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.WindowsAppRuntime.1.3_3000.934.1904.0_x64__8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.WindowsAppRuntime.1.3_3000.934.1904.0_x86__8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x64__8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.WindowsAppRuntime.1.4_4000.1010.1349.0_x86__8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.WindowsCalculator_11.2307.4.0_neutral_split.language-ru_8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.WindowsCalculator_11.2307.4.0_neutral_split.scale-100_8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.WindowsCalculator_11.2307.4.0_x64__8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.WindowsCalculator_2021.2307.4.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.WindowsNotepad_11.2309.28.0_neutral_split.language-ru_8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.WindowsNotepad_11.2309.28.0_neutral_split.scale-100_8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.WindowsNotepad_11.2309.28.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.WindowsNotepad_11.2309.28.0_x64__8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.WindowsStore_22309.1401.5.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:15 AM    <DIR>          Microsoft.WindowsStore_22309.1401.5.0_x64__8wekyb3d8bbwe
11/04/2023  06:55 AM    <DIR>          Microsoft.WindowsTerminal_1.18.2822.0_x64__8wekyb3d8bbwe
11/04/2023  06:55 AM    <DIR>          Microsoft.WindowsTerminal_3001.18.2822.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.Xbox.TCUI_1.24.10001.0_neutral_split.language-ru_8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.Xbox.TCUI_1.24.10001.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.Xbox.TCUI_1.24.10001.0_x64__8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.XboxGameOverlay_1.54.4001.0_neutral_split.scale-100_8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.XboxGameOverlay_1.54.4001.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.XboxGameOverlay_1.54.4001.0_x64__8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.XboxGamingOverlay_6.123.10181.0_neutral_split.language-ru_8wekyb3d8bbwe11/04/2023  06:56 AM    <DIR>          Microsoft.XboxGamingOverlay_6.123.10181.0_neutral_split.scale-100_8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.XboxGamingOverlay_6.123.10181.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:56 AM    <DIR>          Microsoft.XboxGamingOverlay_6.123.10181.0_x64__8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.XboxIdentityProvider_12.95.3001.0_neutral_split.language-ru_8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.XboxIdentityProvider_12.95.3001.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.XboxIdentityProvider_12.95.3001.0_x64__8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.XboxSpeechToTextOverlay_1.21.13002.0_neutral_split.scale-100_8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.XboxSpeechToTextOverlay_1.21.13002.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:53 AM    <DIR>          Microsoft.XboxSpeechToTextOverlay_1.21.13002.0_x64__8wekyb3d8bbwe
11/04/2023  06:54 AM    <DIR>          MicrosoftCorporationII.MicrosoftFamily_0.2.40.0_neutral_~_8wekyb3d8bbwe
11/04/2023  06:54 AM    <DIR>          MicrosoftCorporationII.MicrosoftFamily_0.2.40.0_x64__8wekyb3d8bbwe
11/04/2023  07:24 AM    <DIR>          MicrosoftWindows.Client.WebExperience_423.23500.0.0_neutral_~_cw5n1h2txyewy
11/04/2023  07:24 AM    <DIR>          MicrosoftWindows.Client.WebExperience_423.23500.0.0_x64__cw5n1h2txyewy
11/04/2023  05:39 AM    <DIR>          MovedPackages
05/06/2022  10:24 PM    <DIR>          Mutable
05/06/2022  10:24 PM    <DIR>          MutableBackup
05/06/2022  10:24 PM    <DIR>          Projected
               0 File(s)              0 bytes
              90 Dir(s)  222,359,281,664 bytes free
```

`PowerShell -NoP -C "Get-AppxPackage"`
[Output.txt](https://github.com/Atlas-OS/Atlas/files/13257005/Output.txt)

**Comment by he3als** [comment] 2023-11-12 16:09
Fixed in the latest version

**Closed by he3als** 2023-11-12 16:09 UTC
Labels: bug
