### ISSUE TITLE
Visual Studio 2022 installs, but does not run

### ISSUE THREAD

**Issue by jdpatdiscord** [Atlas-OS/Atlas#600] opened 2023-03-08 10:52 UTC
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

On a fresh installation of Atlas with Windows Store disabled+ OpenShell installed (I don't know if it happens without this too)
Visual Studio 2022 does not run. 

The window of the error says `CiceroUIWndFrame: devenv.exe - Application Error`

And in the Event Viewer, it gives a more detailed log:
![image](https://user-images.githubusercontent.com/42700985/223692120-a3093b0a-61c6-4e88-a747-2623eaa5a516.png)

### Steps to reproduce (if applicable add screenshots)

Install Atlas 21H2 and configure it like I did (Store disabled + OpenShell) to get greatest possible chance of repro,
Install Visual Studio 2022 (in case the modules have anything to do with it, I selected C# and C++ tooling for installation)
See that the install does go fine, however, it will not run.

### Expected behavior

For VS to open, like normal.

### Actual behavior (if applicable add screenshots)

Like so:
![image](https://user-images.githubusercontent.com/42700985/223693662-2b988bc8-9cc8-4cb3-b507-4879ff09e43d.png)

### Atlas Version (1803/20H2/21H2)

21H2

### Desktop information

Ryzen 9 5900X (12c24t), RX 6650 XT, 64GB@3333MT/s and 1TB NVMe SSD

### Additional content

I took a look around on the Atlas Discord for this issue, and found two or three separate instances on the forum, and did not see a fix. I also did not see a similar issue filed on this GitHub. So, to make sure this gets fixed I am filing an issue.

P.S. Older versions of VS2022 did work. I had VS2022 working earlier last year, however it seems an update Microsoft has done has caused it not to work on Atlas. This is reflected in the recent dates of the issues filed in the Atlas Discord support forum.

**Comment by JayXTQ** [comment] 2023-03-08 11:47
VS Community 2022 works fine for me on 22H2 (unreleased). The error provided looks like a vcredists issue, try reinstalling them via the Atlas folder and see if the issue is fixed.

**Comment by jdpatdiscord** [comment] 2023-03-08 11:52
The issue persists after running `Reinstall VCRedists.bat`.

**Comment by JayXTQ** [comment] 2023-03-09 19:47
Can you try reinstalling them via the GitHub repo for vcredists or an alternative method rather than that and see if the issue still persists?

**Comment by jdpatdiscord** [comment] 2023-03-09 23:47
I did install them before running `Reinstall VCRedists.bat`, the x64 one off of Microsoft's website [https://aka.ms/vs/17/release/vc_redist.x64.exe](url)
and that did not work either. Although I fail to understand how this would result in a working VS given that the VS installer installs the runtimes itself.

**Comment by JayXTQ** [comment] 2023-03-12 15:55
Odd, I wouldn't know the solution for 20H2. All I know is that this is fixed in 22H2. When the access comes out to everyone have a try getting it to work then. Or try a different Atlas version for now.

**Closed by JayXTQ** 2023-03-12 15:55 UTC
Labels: bug

**Comment by jdpatdiscord** [comment] 2023-03-12 16:01
Have you considered re-working the versioning done with Atlas? The one-and-done approach is rather silly and keeping open multiple branches for patched and a CI would be much preferable. A rolling release versioning system of a static Windows version is ... what it is.

**Comment by JayXTQ** [comment] 2023-03-12 16:09
We are considering removing all other Atlas versions with the 22H2 update which is why we aren't working on fixing this issue. If we do keep 20H2 this will be reopened so the issue is fixed. Also all versions use the same branch and different XML files depending on what version you want. The XML files are the only difference per version afaik!
