### ISSUE TITLE
Cannot install Japanese locale on 1803

### ISSUE THREAD

**Issue by Rosabis** [Atlas-OS/Atlas#392] opened 2022-12-13 11:58 UTC
### Prerequisites

- [X] This is not a support issue or a question. For any support, questions or help, visit our [Discord server](https://discord.com/servers/atlas-795710270000332800).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://github.com/Atlas-OS/Atlas/wiki) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Description

I tried to install the Japanese language on Atlas OS 1803, but after installing and restarting the computer it is still the English language.

### Steps to reproduce (if applicable add screenshots)

1. Select Add a language in the settings.
2.Select Japanese.
3.Restart your computer.

### Expected behavior

Display Japanese locale after restart.

### Actual behavior (if applicable add screenshots)

All interfaces are still in English . 

### Atlas Version (1803/20H2/21H2)

1803

### Desktop information

-Intel i7 4790k
-DDR3 16GB
-GeForce GTX 980 Ti

**Comment by PencilNavigator** [comment] 2022-12-13 17:55
Duplicate of https://github.com/Atlas-OS/Atlas/issues/319 (same step to install language pack)
if this does not work for you, follow the guide in the atlas Discord when do /language command.

**Comment by PencilNavigator** [comment] 2022-12-13 17:55
It's a Windows bug with 20h2.

https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/language-packs-known-issue.

Try some of the fixes in the docs, or try the guide from ReviOS (the U version) https://www.revi.cc/revios/workspace/lang#h.ry7gga391br1

And if you have the time, reinstall and the first thing you do should be installing languages/keyboard layout.

**Comment by Rosabis** [comment] 2022-12-14 09:13
> It's a Windows bug with 20h2.
> 
> https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/language-packs-known-issue.
> 
> Try some of the fixes in the docs, or try the guide from ReviOS (the U version) https://www.revi.cc/revios/workspace/lang#h.ry7gga391br1
> 
> And if you have the time, reinstall and the first thing you do should be installing languages/keyboard layout.

1.I first tried the method provided by # 319, which showed a successful installation, but the language was still English instead of Japanese 
2. I tried the method provided by ReviOS, and after restarting, the system prompted that the upgrade failed .

**Comment by PencilNavigator** [comment] 2022-12-14 16:05
> > It's a Windows bug with 20h2.
> > https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/language-packs-known-issue.
> > Try some of the fixes in the docs, or try the guide from ReviOS (the U version) https://www.revi.cc/revios/workspace/lang#h.ry7gga391br1
> > And if you have the time, reinstall and the first thing you do should be installing languages/keyboard layout.
> 
> 1.I first tried the method provided by # 319, which showed a successful installation, but the language was still English instead of Japanese 2. I tried the method provided by ReviOS, and after restarting, the system prompted that the upgrade failed .

https://github.com/Atlas-OS/Atlas/issues/319 the language pack in this issues is Simplified Chinese only, you will need to find the japanese language pack yourself and do the same step to install.

**Closed** 2022-12-17 18:10 UTC
Labels: bug
