### ISSUE TITLE
[FEATURE REQUEST] - Make a script to get the data usage settings page back

### ISSUE THREAD

**Issue by githubUser712934** [Atlas-OS/Atlas#819] opened 2023-06-04 00:06 UTC
### What is your feature request regarding to?

AtlasOS

### Is your feature request related to a problem? Please describe.

AtlasOS removes the data usage settings page, it's blank (please see images in additional context), I don't think this is a bug, it's probably just another thing removed to "debloat" windows.

Some gamers connect to the internet through a limited mobile data hotspot.

I searched the forums, and the github, and I could not find a thread about data usage, there is one on the discord, but it has been buried by other issues and ignored, there is no solution in that post. https://discordapp.com/channels/795710270000332800/1109831494375055401

### Describe the solution you would like.

I would like a script to be created to get the data usage settings page back, and for it to be included in atlas 0.3 configuration folders, no different from the many other things that can be returned with the included scripts.

### Describe alternatives you have considered.

I have considered that it might be related to a service, but the data usage service was not disabled by atlas, it was already running and set to automatic startup.

I have looked up the issue in windows 10 generally and the best I can find is people suggesting dism commands that might extensively break atlas's changes to windows, I only need data usage back.

"Run the basic Windows Repairs. Open cmd.exe with Run as Administrator and run both: (a) dism.exe /online /cleanup-image /restorehealth (b) SFC /SCANNOW"

https://superuser.com/questions/1548677/windows-10-data-usage-not-showing-up-properly

https://answers.microsoft.com/en-us/windows/forum/all/data-usage-setting-page-is-showing-nothing/99c6e59a-08b9-4191-b41f-c0b32f64babd

I have used registry finder to search for data usage but do not know what to make of the results.
![image](https://github.com/Atlas-OS/Atlas/assets/125717219/5c21f73b-cb14-434a-bc5a-a9b161981509)

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I understand that not filling out this template will lead to the issue being closed.

### Additional context.

![image](https://github.com/Atlas-OS/Atlas/assets/125717219/e54a0776-09b6-4a26-a689-e702104f5540)
![image](https://github.com/Atlas-OS/Atlas/assets/125717219/a7e0ab48-3020-4aa7-83bb-4d70c5834cb3)
![image](https://github.com/Atlas-OS/Atlas/assets/125717219/6e31ee27-dfc8-4962-8c49-c07634fcc780)
![image](https://github.com/Atlas-OS/Atlas/assets/125717219/4d9c0353-50a6-47eb-997a-754bfeebb185)

**Comment by Bassil-GG** [comment] 2023-07-13 17:01
MOM I'm on TV

**Comment by JayXTQ** [comment] 2023-08-02 19:24
@he3als @Xyueta

**Comment by Xyueta** [comment] 2023-08-02 19:25
I have not yet been able to find the correct and fully working solution

**Comment by Faresgmr** [comment] 2023-08-24 05:15
I have it broken on W11 (not using atlas) and it seems enabling the DPS Service (Diagnostic Policy Service) fixes the broken page but it still doesn't count the data usage (could be because i have something else broken tho because my internet usage per app in task manager is stuck at 0mb/s in task manager, performance tab works fine)

**Comment by Xyueta** [comment] 2023-08-24 22:01
Confirmed. 

Fixed in: https://github.com/Atlas-OS/Atlas/commit/4c59ccb721adc4c30abbc94d35ee26627a5ae3d2.

**Closed by Xyueta** 2023-08-24 22:01 UTC
Labels: enhancement
