### ISSUE TITLE
Slow Internet when using Mullvad on Atlas

### ISSUE THREAD

**Issue by FeyrisTan** [Atlas-OS/Atlas#321] opened 2022-11-26 21:32 UTC
Using Mullvad on Atlas results in slow, buggy internet. (fresh install)
Tested multiple times on normal windows (same winver) and connected to the exact same servers without any problems.
This only happens on atlas.
Steps tried:

Update ethernet driver
Reset Network Tweaks to Windows Default
Turned on "Enable VPNs"

**Comment by Alino001** [comment] 2022-11-26 21:33
Did you install the wifi driver

**Comment by FeyrisTan** [comment] 2022-11-26 21:34
I dont have wifi. Only ethernet which is updated.

**Comment by Alino001** [comment] 2022-11-26 21:35
Ah ok

**Comment by Alino001** [comment] 2022-11-26 21:36
Hmmm

**Comment by Alino001** [comment] 2022-11-26 21:37
idk

**Comment by JayXTQ** [comment] 2022-12-01 13:21
My Mullvad worked fine last time I used it, what version of Atlas are you running and are you on default settings on Mullvad or have you done some configuration?

**Comment by JayXTQ** [comment] 2022-12-02 20:38
Back again, Mullvad is working fine for me on latest version and Atlas version 20H2

**Comment by SyrmGIT** [comment] 2022-12-03 00:00
Closing this issue due to error not being reproduced by commenters (please look into the issue more)

**Closed by SyrmGIT** 2022-12-03 00:00 UTC
Labels: bug
