### ISSUE TITLE
[BUG REPORT] - faultrep.dll missing.

### ISSUE THREAD

**Issue by Hybes** [Atlas-OS/Atlas#685] opened 2023-04-14 12:48 UTC
### Description

Some games such as Call of Duty: Black Ops 2, Modern Warfare 2 and World at War, error when loading with:
Unable to load import 'ReportFault' from module 'faultrep.dll'.
Preventing the games from opening and in some cases, not opening at all.

### Steps to reproduce (add screenshots if applicable)

Here's an error output from using Plutonium.
![image](https://user-images.githubusercontent.com/53020786/232047412-1fdcc4ce-9795-410b-bc24-b86ebfa88193.png)
When the game is launched normally through Steam it just closes straight away and never opens.

### Expected behavior

Game should open and not provide this error.

### Actual behavior (add screenshots if applicable)

Game crashes, or doesnt open

### Atlas Version

Atlas 10 22H2

### Desktop information

RYZNE 9 5900X
64gb RAM
GIGABYTE 3080
M.2 and SSD tested.

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by CreepTron365** [comment] 2023-04-15 03:34
I can confirm this is an issue caused by the Atlas playbook as I had the same issues with certain call of duty titles. Using the same game installs on a vanilla Windows 10 dualboot install did not present this issue and was not resolved after reinstalling game files. The missing file required to play these titles is 'faultrep.dll' located at 'C:\Windows\SysWOW64'. I extracted the missing file from the install.wim in the installation iso using 7zip and placed it in the correct location on my Atlas install to resolve this issue for the meantime.

Hope this helps,
-CreepTron365

**Comment by Hybes** [comment] 2023-04-15 08:29
@CreepTron365 Hi, that's a great response thanks, so if i download a fresh ISO of 22H2 and unzip it I should be able to find this DLL file?

**Comment by CreepTron365** [comment] 2023-04-15 08:31
@Hybes Hi, Yes this is correct. If you need a hand, feel free to DM me on Discord to thePineapple🍍#1455

**Comment by Xyueta** [comment] 2023-04-15 08:45
Possible fixed in https://github.com/Atlas-OS/Atlas/commit/3f4b8bd60f3b7b183593d35a1e4e24a9f6ffee95.

**Comment by Hybes** [comment] 2023-04-15 08:47
> Possibly fixed in https://github.com/Atlas-OS/Atlas/commit/3f4b8bd60f3b7b183593d35a1e4e24a9f6ffee95.

Great, how could i implement this? or shall i proceed to gathering the file from the ISO?

**Comment by Xyueta** [comment] 2023-04-15 09:41
Works fine. It will be available in the next release.

**Closed by Xyueta** 2023-04-15 09:41 UTC
Labels: bug, pending
