### ISSUE TITLE
[BUG] - Installation over RDP fails with cryptic errors

### ISSUE THREAD

**Issue by dark-penguin** [Atlas-OS/Atlas#1050] opened 2024-03-09 13:37 UTC
### Description

If you run AME Wizard over RDP, then it "Finishes with some errors". The errors say something about the user tokens and directories not existing, but not even I could guess that it means "installation over RDP is not supported".

While it's not a major use case, it may be quite common for some sysadmins like me who often install things remotely. It would be nice to try acquiring that user token before installation, and warning that installation over RDP is not supported if that fails.

To clarify, the problem I see here is not that installation over RDP is not supported - it's that I was confused for quite some time while trying to figure out why did it fail, even though it just worked fine on my test VM.

### Steps to reproduce

1. Clean Windows 10 Pro installation, with nothing but drivers installed
2. In the Advanced System Properties, "Allow remote connections" - "from any client version"
3. Connect over RDP, launch AME Wizard, install as usual

### Expected behavior

Before installation, there should be a warning that installing Atlas OS over RDP will fail.

### Actual behavior

"Installation finished with some errors \<error log\>"

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

i7-3820
32GB RAM
Noname (Vaseky) NVMe SSD, 240 GB
AMD Radeon R9 290

**Comment by Ast3risk-ops** [comment] 2024-03-09 14:00
So it finished with errors, did you reboot and check that all was there?

**Comment by dark-penguin** [comment] 2024-03-09 14:16
I've rebooted, saw that indeed a lot of things have failed, and reran the wizard. The wizard noticed that the previous installation has failed, and did it all again.
But that failed again, because I was still over RDP. With the same things in the logs. So, after a while, I've figured it out, reran the wizard locally, and then everything was installed properly.
[3-09-2024-Atlas-AtlasOS.zip](https://github.com/Atlas-OS/Atlas/files/14546540/3-09-2024-Atlas-AtlasOS.zip)

**Comment by Ast3risk-ops** [comment] 2024-03-09 14:20
In case you're too lazy to download that, here you go: https://shares.asterisk.lol/share/AI18KUWj

**Comment by jonatino** [comment] 2024-04-15 02:28
@dark-penguin until this bug is fixed used https://github.com/rustdesk/rustdesk

You can set it up to support direct LAN connections and it's as responsive if not more than RDP in my experience.

**Comment by hcocoa** [comment] 2024-05-09 06:36
> Hi - this is a known AME Wizard issue and will be fixed in the next AME Wizard release.
> 
> To install Atlas currently, you would have to use an alternative to RDP or do it locally.

Fainting, I've reinstalled it over and over again, only to find out that the issue was caused by RDP. 

Please clearly state on the homepage that installation via RDP is not supported!

**Comment by Ast3risk-ops** [comment] 2024-05-09 11:48
> Fainting, I've reinstalled it over and over again, only to find out that the issue was caused by RDP.
> 
> Please clearly state on the homepage that installation via RDP is not supported!

It's an AME bug.

**Comment by he3als** [comment] 2024-05-09 15:44
> Please clearly state on the homepage that installation via RDP is not supported!

![image](https://github.com/Atlas-OS/Atlas/assets/65787561/e214eb6d-7929-4909-a783-599b57d6a08d)

**Comment by he3als** [comment] 2024-06-12 17:04
You can use the latest AME Wizard beta at https://t.me/+BNgSXRsy2-FmN2Qx, which fixes this issue. There should be a new stable AME Wizard release soon as well.

Note that feedback is encouraged and that these betas might introduce other issues.

**Comment by he3als** [comment] 2024-07-04 21:13
Fixed in AME Wizard v0.7.5

**Closed by he3als** 2024-07-04 21:13 UTC
Labels: bug, ame wizard, fixed next release, workaround avaliable
