### ISSUE TITLE
can not paly new moder warefaer 

### ISSUE THREAD

**Issue by Shadowolf22** [Atlas-OS/Atlas#358] opened 2022-12-05 06:54 UTC
# Not filling out this template will lead to the issue being closed

**Describe the bug**
A clear and concise description of what the bug is. Providing an error code is highly recommended.

**To reproduce**

**Expected behavior**

**Screenshots**

**Desktop Info (please complete the following information):**

- CPU [Intel or AMD, include specifics]
- System Drive Type
- Version [1803/20H2/21H2 FACEIT]

**Additional context**

can not play call of duty moderware lack a update that the game requirements

**Comment by JayXTQ** [comment] 2022-12-05 07:22
I do not understand? Can you please attach images of the issue like asked in the template. Also, next time try to follow it

**Comment by PencilNavigator** [comment] 2022-12-05 09:48
Duplicate of https://github.com/Atlas-OS/Atlas/issues/281.

**Closed** 2022-12-05 09:49 UTC
Labels: bug
