### ISSUE TITLE
[BUG] - PATH variable is overwritten

### ISSUE THREAD

**Issue by ChuonChuonBayThap** [Atlas-OS/Atlas#1076] opened 2024-04-12 15:18 UTC
### Description

- [This is what i said in previous bug report: ](https://github.com/Atlas-OS/Atlas/issues/1072)
After install the new version of AtlasOS, i cant run .cmd files: the cmd window shows up and then close immediently. I tried to open CMD but some common commands does not work (image below)
- I reported this bug in https://github.com/Atlas-OS/Atlas/issues/1072 but it's closed because my Windows edition is IoT Enterprise which is not recommended. 
![image](https://github.com/Atlas-OS/Atlas/assets/155883444/e5fc9c14-8b9a-4419-817c-a020443b56e2)
- Then I tried to reinstall AtlasOS on my clean Windows 11 Pro but i still get that bug, pls take a closer look. 
![image](https://github.com/Atlas-OS/Atlas/assets/155883444/fde0368a-d60a-4bae-81f1-c6884d3e76cd)

### Steps to reproduce

1. Double click to open a .cmd file or run some commands in cmd.

2. Watch it doesnt work like you expected.

### Expected behavior

It supposes to run normally.

### Actual behavior

![image](https://github.com/Atlas-OS/Atlas/assets/155883444/effecbc7-d9d6-4897-ad7e-4a4f16c71246)
![image](https://github.com/Atlas-OS/Atlas/assets/155883444/a6d68c50-4e94-4373-ad22-f3ee6b9ec246)

### Atlas Edition

Atlas for Windows 11 23H2

### Desktop information

Operating System: Windows 11 Pro
System Manufacturer: Acer
System Model: Aspire A715-43G
Processor: AMD Ryzen 5 5625U with Radeon Graphics (12 CPUs), ~2.3GHz
Memory: 24576MB RAM
Card name: NVIDIA GeForce RTX 3050 Laptop GPU

### Additional content

[Update] Simply fixed it by looking up missing paths in [this link](https://www.elevenforum.com/t/complete-list-of-environment-variables-in-windows-11.11212) and adding them back, those commands now work normally again.

**Comment by Ast3risk-ops** [comment] 2024-04-12 16:05
btw cmd commands don't use `-`, they use `/` (so help is usually `/?`) However dism should work as normal, so check your PATH (if cmd is crashing, it's probably because of these command not found errors, you may also want to try changing your default terminal emaulator to Windows Terminal as is the win11 default)

**Comment by gitchuon** [comment] 2024-04-12 16:14
> btw cmd commands don't use `-`, they use `/` (so help is usually `/?`) 
yeah i was wrong at that point, but what ever it is, the 'sfc' still can not be recognized. i tried everthing i could but nothing get better, maybe i need to reinstall my windows again and wait for new atlas version...

**Comment by Ast3risk-ops** [comment] 2024-04-12 16:15
> > btw cmd commands don't use `-`, they use `/` (so help is usually `/?`)
> 
> yeah i was wrong at that point, but what ever it is, the 'sfc' still can not be recognized. i tried everthing i could but nothing get better, maybe i need to reinstall my windows again and wait for new atlas version...

You may not have reinstalled correctly, what were your steps?

**Comment by gitchuon** [comment] 2024-04-12 16:25
> what were your steps?

just like everyone else: install ventoy on an usb stick, boot up an official windows  and start to install windows normally. i had run those commands normally before installed Atlas so i pretty sure that Atlas causes this bug.

**Comment by Ast3risk-ops** [comment] 2024-04-12 18:04
> > what were your steps?
> 
> just like everyone else: install ventoy on an usb stick, boot up an official iso and start to install windows normally. i had run those commands normally before installed Atlas so i pretty sure that Atlas causes this bug.

That's not the steps, and if you're gonna use a USB, wipe your disk to ensure the install is clean (you don't even need to use a USB)

**Comment by gitchuon** [comment] 2024-04-13 02:13
> That's not the steps

That's the MAIN STEPS I did, I just want you to understand that I know how to install Windows correctly, and the bug only appears after installed AtlasOS

**Comment by Ast3risk-ops** [comment] 2024-04-13 02:15
> > That's not the steps
> 
> That's the MAIN STEPS I did, I just want you to understand that I know how to install Windows correctly, and the bug only appears after installed AtlasOS

During USB install if you just clicked your C: drive you didn't fully wipe windows, so reinstall again, and wipe your drive (erase all partitions)

**Comment by gitchuon** [comment] 2024-04-13 02:55
> During USB install if you just clicked your C: drive you didn't fully wipe windows

Nahh I didnt do that bro, i deleted every windows partitions and used `diskpart` to wipe my drive so pls understand that **i know how to install windows correctly**. The bug only appears after installing AtlasOS (2 times in 2 different windows edition!!).

**Comment by trolljoe** [comment] 2024-04-13 03:08
are you sure you didn't delete anything from PATH? i have tried 0.4 and sfc, dism all work fine

**Comment by gitchuon** [comment] 2024-04-13 03:44
> are you sure you didn't delete anything from PATH?

yes, i ran some .cmd files and those command before installing AtlasOS so 
im pretty sure that everything was run normaly

> i have tried 0.4 and sfc, dism all work fine

that's so weird, i try 0.4 on 2 different editons of windows (both are clean installation) and still get that bug...

**Comment by he3als** [comment] 2024-04-13 12:21
Can you send the `TIOutput.txt` in the Atlas folder inside of `%ProgramData%\AME\Logs`, please?

**Comment by gitchuon** [comment] 2024-04-13 16:16
Unfortunately, I have just reinstalled Windows and no longer have that file 😔. I will try installing AtlasOS in a VM to see if the bug appears again; then I will send you the file. If it doesn't, I will close this report. Thanks for your reply.

(Btw, I really love your Edge remover script, it helps me a lot 🙌).

**Comment by gitchuon** [comment] 2024-04-14 09:06
> Can you please send the TIOutput.txt in the Atlas folder inside of %ProgramData%\\AME\\Logs?

Here is the file you need
![TIOutput.txt](https://github.com/Atlas-OS/Atlas/files/14970051/TIOutput.txt)

**Comment by Ast3risk-ops** [comment] 2024-04-14 12:43
> TIOutput.txt

Pasted: https://paste.asterisk.lol/raw/ikecawunol

**Comment by gitchuon** [comment] 2024-05-06 15:08
@Ast3risk-ops @he3als
- I think I found out what causes this error. Maybe while AtlasOS is modifying system variables, instead of adding some new paths, it replaces them (or deletes them). So that's why in 'Environment Variables'/System variables/path, I only see nothing but AtlasOS's paths.
- I simply fixed it by looking up missing paths in this link and adding them back, those commands now work normally again.
![IMG_20240506_220359~2.jpg](https://github.com/Atlas-OS/Atlas/assets/155883444/a975c705-5bf1-4294-b7d2-037e70293c8f)

![IMG20240506220546.jpg](https://github.com/Atlas-OS/Atlas/assets/155883444/a29ea480-f5dc-4312-a028-22ca13438e7f)

**Comment by he3als** [comment] 2024-05-07 13:35
Atlas doesn't replace the PATH variable, it just appends to it. https://github.com/Atlas-OS/Atlas/blob/main/src/playbook/Configuration/atlas/start.yml#L9

I'm not too sure what could be wrong or how to reproduce your issue.

**Comment by Xyueta** [comment] 2024-05-31 19:34
Closing as resolved.

Thanks.

**Comment by he3als** [comment] 2024-06-01 16:58
I'm going to re-open this as I think there could be more investigation regarding alternatives to getting the PATH variable.

**Comment by Danalytics-dan** [comment] 2024-06-02 15:40
My atlasOS install is fine with all PATHs and cmds all work as expected. (I installed about a week ago with a fresh install because my last windows was broken coincidentally the paths)

**Comment by he3als** [comment] 2024-06-08 13:47
I've rewritten the function that adds to the PATH variable for the next release. Although I'm unsure how the previous implementation caused issues, it should be more reliable now. If this doesn't fix it, then I'm not sure what else can be done as it can't be reproduced. https://github.com/Atlas-OS/Atlas/commit/3aac4b82d7bf9d4fd0e9347cb6d3eeeb61e6b53d

You can test an experimental build of it here: https://github.com/Atlas-OS/Atlas/actions/runs/9429116816

Remember that these builds are not meant for daily driving and should only be used for testing. There are unfinished things as well as bugs.

**Comment by he3als** [comment] 2024-06-08 19:02
I've rewritten the function that adds to the PATH variable for the next release. Although I'm unsure how the previous implementation caused issues, it should be more reliable now. If this doesn't fix it, I'm unsure what else can be done as it can't be reproduced. https://github.com/Atlas-OS/Atlas/commit/3aac4b82d7bf9d4fd0e9347cb6d3eeeb61e6b53d

You can test an experimental build, which includes it here: https://github.com/Atlas-OS/Atlas/actions/runs/9429700703

Remember that these builds are not meant for daily driving and should only be used for testing. There are unfinished things as well as bugs.

**Comment by he3als** [comment] 2024-06-11 20:11
I'm going to close this issue, but if there are any testing results, just comment.

**Closed by he3als** 2024-06-11 20:11 UTC
Labels: bug, can't reproduce

**Comment by awksie** [comment] 2024-08-17 15:04
Just reporting in, I ran into this bug today using the latest AME Wizard (0.7.5 Beta?) and Atlas playbook on a fresh install of Windows 11 Home using freshly-created install media with a newly-downloaded copy of Windows (from Microsoft.)

After Atlas setup, the system Path variable was set to only include:
`PATH=;C:\Windows\AtlasModules;C:\Windows\AtlasModules\Apps;C:\Windows\AtlasModules\Other;C:\Windows\AtlasModules\Tools;C:\Windows\AtlasModules\Scripts`

**Comment by Ast3risk-ops** [comment] 2024-08-17 15:07
> Windows 11 Home

https://docs.atlasos.net/install-faq/windows-home/

We don't support Home, try with Pro.

**Comment by awksie** [comment] 2024-08-17 15:21
I don't have the option on that machine, as it has the key embedded and
will not accept Pro. In any case, while I do understand the desire to head
off bug reports in unsupported configurations, I don't really think that
has anything to do with this issue. :)

I don't need support, as I've already resolved the problem by manually
replacing the path variable, but I wanted to provide the report so that you
know that this can still happen to people despite the issue being closed.

**Comment by Ast3risk-ops** [comment] 2024-08-17 15:46
However the issue might be specific to Home, you can override the key lock using a USB (might work without one too if the iso is extracted) and the [`ei.cfg`](https://cdn.jsdelivr.net/gh/pre-book/prebook@main/ei.cfg) file (place it inside the `sources` folder, it will force the edition picker to appear)

**Comment by he3als** [comment] 2024-08-17 23:34
I doubt this issue is related to Windows Home, but the logic for adding to the PATH variable has been updated for v0.5 anyway, so it should be fixed for the next release.

Did you install any software before installing Atlas? Or did you install Atlas without following the [installation guide](https://docs.atlasos.net/getting-started/installation/)?

**Comment by awksie** [comment] 2024-08-17 23:48
I followed the guide, although I have installed Atlas many times before on
many other machines.
1) Prepare image using Rufus
2) Install on clean (no volumes present) drive, in this case a raid-0 of
two PCIe 4.0 SSDs (don't get on my case, that's how Dell provisioned the
machine to begin with)
2.1) Use a local administrator account (not the built-in one)
3) Install video and Ethernet drivers
4) Connect internet and perform all Windows updates including drivers
5) Pause updates and disable required security features
6) Install Atlas playbook
7) After reboot, apply tweaks from Atlas folder on desktop ← this is where
things went awry

Also, this is really for a separate issue, but I selected Firefox as my
browser and Atlas failed to install it, leaving me with no browser, which
was a mild pain, lol.

**Comment by he3als** [comment] 2024-08-17 23:55
Can you send your logs from `C:\ProgramData\AME\Logs`?

**Comment by awksie** [comment] 2024-08-18 00:50
I most certainly can:
[Output.txt](https://github.com/user-attachments/files/16646863/Output.txt)

Looks like the path issue may have caused the Firefox issue? Wonder what else it broke.
