### ISSUE TITLE
[BUG?] - Roblox doesn't open

### ISSUE THREAD

**Issue by Icey67** [Atlas-OS/Atlas#1178] opened 2024-08-09 19:19 UTC
### Before continuing...

- [X] I agree to follow Atlas' [Code of Conduct](https://github.com/Atlas-OS/.github/blob/main/profile/CODE_OF_CONDUCT.md)
- [X] I have searched our [issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to verify that the issue hasn't been reported already
- [X] I have searched the [Atlas documentation](https://docs.atlasos.net) beforehand for a solution
- [X] I am on the latest version of Atlas, and didn't do an unsupported upgrade

### Description

I am not sure if this is a bug on Atlas' part but I try to launch Roblox,
and you guessed it, it doesn't launch at all.
It shows up in Task Manager using _some_ CPU but yet otherwise it just doesn't show up.

### Steps to reproduce

1. Navigate to `C:\Users\<username>\AppData\Local\Roblox\Versions\version-<string of numbers and letters>\`
2. Double click on `RobloxPlayerBeta.exe`
3. absolutely nothing.

Or execute via CMD or Run with the following:
`C:\Users\<username>\AppData\Local\Roblox\Versions\version-<string of numbers and letters>\RobloxPlayerBeta.exe --app`

### Expected behavior

Normally the app opens up to the login screen, or the main menu.

### Actual behavior

nothing happens.

### Atlas Edition

Atlas for Windows 10 22H2

### Desktop information

AtlasOS Version 0.4.0
CPU: AMD Phenom II X6 1090T 3.20GHz
RAM: 16GB DDR3-1333 DIMM
Motherboard: ASUSTek M5A87
GPU: AMD Radeon RX 580 2048SP, Driver version: AMD Software Adrenaline Edition 24.7.1
Storage: 1TB SanDisk SSD, 512GB Hitachi? HDD
(i am not really sure about the storage)

### Additional content

Here a list of everything I tried so far:

- Trying to figure it out with Process Monitor
- - When I try to launch Roblox with Process Monitor open, it sends an error that PROCMON24.SYS/PROCMON23.SYS is running
- Reinstalling Roblox
- Rebooting
- Secure Boot and/or TPM 2.0 is not possible
- Created new Local Account

I believe this is due to Roblox's new Anti Cheat or something, and even somehow, when making a new local account and launching Roblox from there did work.
Though I do **NOT** want to migrate from my main account to a different local one because,

1. it would be too much of a hassle
2. Atlas' configuration gets reverted in the new account??*

I would like to blame it on the fact that my PC hardware is pretty old (but that doesn't seem to be an issue, since it is working on a newly created local account). It might much more likely be an issue with Atlas' configuration that puts it off.

**Comment by Ast3risk-ops** [comment] 2024-08-09 20:34
Pretty sure this is a duplicate of several issues.

Please try the fixes listed here before opening an issue: https://docs.atlasos.net/general-faq/roblox-not-opening/

**Comment by JayXTQ** [comment] 2024-08-09 20:35
Use the document above.

**Closed by JayXTQ** 2024-08-09 20:35 UTC
Labels: bug

**Comment by Icey67** [comment] 2024-08-09 20:38
Excuse me, but I indeed tried to follow the above linked document with no real good results, and I have only seen 3 issues mentioning specifically Roblox.

**Comment by Ast3risk-ops** [comment] 2024-08-09 20:39
> Excuse me, but I indeed tried to follow the above linked document with no real good results, and I have only seen 3 issues mentioning specifically Roblox.

3 is more than 0. Please do not open duplicate issues.

**Comment by Icey67** [comment] 2024-08-09 20:40
thank you but this has been very unhelpful, I may want to consider not using atlas in the future.

**Comment by Ast3risk-ops** [comment] 2024-08-09 20:40
> Excuse me, but I indeed tried to follow the above linked document with no real good results, and I have only seen 3 issues mentioning specifically Roblox.

There's waaay more posts mentioning Roblox on https://forum.atlasos.net you can check.

**Comment by Icey67** [comment] 2024-08-09 20:41
oh.

**Comment by Ast3risk-ops** [comment] 2024-08-09 20:42
> thank you but this has been very unhelpful, I may want to consider not using atlas in the future.

?

**Comment by JayXTQ** [comment] 2024-08-09 20:45
Or bloxstrap, that usually works

**Comment by Ast3risk-ops** [comment] 2024-08-09 20:47
> bloxstrap

https://bloxstrap.pizzaboxer.xyz/

Put links Jay.

**Comment by Icey67** [comment] 2024-08-09 20:57
I am running into this same issue with bloxstrap, luckily, bloxstrap does have log files and so I shall pursue this issue elsewhere.
