### ISSUE TITLE
[BUG] - Wake On Lan not working

### ISSUE THREAD

**Issue by MatthusKakttus** [Atlas-OS/Atlas#965] opened 2023-11-13 12:27 UTC
### Description

Before using Atlas OS I configured Windows and my BIOS to listen to magic packet to start the PC (WOL). Everything is supposed to be delegated to the BIOS, the BIOS could wake the PC. After Atlas OS installation, it isn't working anymore. 
Hibernation is off, and when I shutdown the PC from Windows (with the power off button or "shutdown /s"). I'm not able to wake on Lan. 
Interesting fact, when I force shutdown by long pressing the physical power button, I'm able to wake on LAN. 
I guess this has to do with in which power state the PC goes when pressing shutdown but I was not able to fix it by myself.

### Steps to reproduce (add screenshots if applicable)

1. Enable wake on Lan in BIOS settings
2. Enable wake on Lan in device manager->network adapter->Ethernet->properties
3. Getting the Mac address
4. Shutdown the PC
5. From another device sending Wake On Lan magic packet with the correct MAC address

### Expected behavior

The PC should start when receiving a magic packet as it did before installing Atlas OS.

### Actual behavior (add screenshots if applicable)

PC not starting when sending WOL magic packet after proper shutdown from Windows.

### Atlas Version

Atlas 10 22H2

### Desktop information

- Processor Intel core i5-8400
- Ram 16GB DDR4
- Storage SSD 1TB
- Graphic Card Nvidia GTX 1060 6GO
- Motherboard MSI Z370I GAMING PRO CARBON AC 
- Ethernet Network Adapter Built-in motherboard

### Requisites

- [X] This is not a support issue or a question. For any support, questions or help, join our [Discord server](https://discord.atlasos.net).
- [X] I performed a [cursory search of the issue tracker](https://github.com/Atlas-OS/Atlas/issues?q=is%3Aissue) to avoid opening a duplicate issue.
- [X] I checked the [documentation](https://docs.atlasos.net) to understand that the issue I am reporting is not normal behavior.
- [X] I understand that not filling out this template correctly will lead to the issue being closed.

**Comment by Xinelin** [comment] 2023-11-19 12:07
My WOL also not working after install Atlas AME

**Comment by Demyshka** [comment] 2023-11-22 11:09
Temporarily you can set windows network setting in C:\Windows\AtlasDesktop\8. Troubleshooting\Network, its called ''Reset Network to Windows Default''

**Comment by MatthusKakttus** [comment] 2023-11-22 11:25
Yeah I already did that but it's still not working =_=
I think it has to do with the power down state S5, S4, S3 etcc more than with network settings.
When I shutdown my computer from bios I can use wake on lan so maybe when shutting down Atlas OS / Windows we should get in the same state as when shutting down from bios ?

**Comment by jameschubbuck** [comment] 2023-12-06 03:08
I have been having the same issue. I am using sunshine/moonlight with a headless computer for gaming and WOL does not work. I have properly configured my network adapter, bios, etc., a fix would be greatly appreciated as this might be a dealbreaker for me.

**Comment by MatthusKakttus** [comment] 2023-12-06 13:12
I did not find the fix for WOL, until this is resolved I re-installed windows and applied ReviOS playbook instead of AtlasOS. I don't know all the differences between the two but for my usage case ReviOS is as good as AtlasOS (plus Wake On Lan is working).

**Comment by Ast3risk-ops** [comment] 2023-12-06 13:15
> Yeah I already did that but it's still not working =_= I think it has to do with the power down state S5, S4, S3 etcc more than with network settings. When I shutdown my computer from bios I can use wake on lan so maybe when shutting down Atlas OS / Windows we should get in the same state as when shutting down from bios ?

So you're on 0.3? Just wanna clarify.

**Comment by MatthusKakttus** [comment] 2023-12-06 13:28
I don't have the installation anymore so I can't tell you, but I installed it 3 weeks ago, when I wrote the issue, and I installed the latest release at that time. So it was v0.3.x ... Sorry I can't help you more now that I don't have access to AtlasOS, but hopefully the others with the same problem will be able to help you find the bug.

**Comment by jameschubbuck** [comment] 2023-12-06 15:15
This didn't work for me.

**Comment by Brainwasher06** [comment] 2023-12-06 22:32
Reverting to default work for me. 

Before trying i made sure that every settings related to WOL was enabled£. (mostly network card advanced settings and in device manager)

**Comment by he3als** [comment] 2024-01-14 00:15
## Temporary solution

Run the **Reset Network to Windows Default.cmd** in the 'Troubleshooting' folder.

![vmconnect_h6IH0GmQ1Y](https://github.com/Atlas-OS/Atlas/assets/65787561/e16541d2-4419-4099-9336-828dd4e53001)

**Comment by fmaxyou** [comment] 2024-02-05 06:23
> ## Temporary solution
> Run **Reset Network to Windows Default.cmd** in the **8. Troubleshooting\Network** folder.
> 
> ![vmconnect_h6IH0GmQ1Y](https://private-user-images.githubusercontent.com/65787561/296522702-e16541d2-4419-4099-9336-828dd4e53001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTM4ODcsIm5iZiI6MTcwNzExMzU4NywicGF0aCI6Ii82NTc4NzU2MS8yOTY1MjI3MDItZTE2NTQxZDItNDQxOS00MDk5LTkzMzYtODI4ZGQ0ZTUzMDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA2MTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNzEwMGUyNDFmMTM4MzJmNzJjMWQ0ODQyNGJhZjUwOGI4MDJkYTdlNzhiYWVlNDhkMTI0NmRjOGRlYzFmOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I54uVS_5f6UFpC7TCl6l7Grj2JaGB963cQ7XyYiWvz4)

This didn't work for me.

**Comment by Linuxydable** [comment] 2024-02-07 04:19
> ## Temporary solution
> Run **Reset Network to Windows Default.cmd** in the **8. Troubleshooting\Network** folder.
> 
> ![vmconnect_h6IH0GmQ1Y](https://private-user-images.githubusercontent.com/65787561/296522702-e16541d2-4419-4099-9336-828dd4e53001.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNzk4MDUsIm5iZiI6MTcwNzI3OTUwNSwicGF0aCI6Ii82NTc4NzU2MS8yOTY1MjI3MDItZTE2NTQxZDItNDQxOS00MDk5LTkzMzYtODI4ZGQ0ZTUzMDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDA0MTgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZWYzYjhhYTQxZDJhOTBkOGYyZmZiMjg2YThjZWQ1NTkyNzNhMDk5MDI3ZDJjYzhmNWI3OTllNjdmZWVmNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Ch2ptEoi1ub2JXw_o8AFwMiwzfZGCA6Qmm8hlGoFS8)

Thanks @he3als, this works perfectly for me !

**Comment by fmaxyou** [comment] 2024-02-07 05:42
> Make sure that Wake on Lan is enabled in your network adapter settings.

Thanks! The problem is with my BIOS settings. Now it works for me!

**Comment by he3als** [comment] 2024-02-07 09:54
Still not fixed, keeping it open until next release when Wake on Lan isn't disabled

**Comment by Marc--** [comment] 2024-02-08 20:25
> > Make sure that Wake on Lan is enabled in your network adapter settings.
> 
> Thanks! The problem is with my BIOS settings. Now it works for me!

Hi @fmaxyou , I've just installed AtlasOS and have the exact same problem! 

My wol was working just before I install AtlasOS.

It's working from sleep mode (hope it's the good term in English, for me it's "Mise en veille ").

I revert to "network default" but if I shutdown the computer, no WOL. LEDs are off on the network card, bios "wake on pcie" enabled.

Can you explain the changes you made to your bios ?

**Comment by Xyueta** [comment] 2024-02-09 16:14
Fixed in the latest commit.

**Closed by Xyueta** 2024-02-09 16:14 UTC
Labels: bug

**Comment by fmaxyou** [comment] 2024-02-13 14:56
> > > Make sure that Wake on Lan is enabled in your network adapter settings.
> > 
> > 
> > Thanks! The problem is with my BIOS settings. Now it works for me!
> 
> Hi @fmaxyou , I've just installed AtlasOS and have the exact same problem!
> 
> My wol was working just before I install AtlasOS.
> 
> It's working from sleep mode (hope it's the good term in English, for me it's "Mise en veille ").
> 
> I revert to "network default" but if I shutdown the computer, no WOL. LEDs are off on the network card, bios "wake on pcie" enabled.
> 
> Can you explain the changes you made to your bios ?

Hi there, I was watching this video: https://www.youtube.com/watch?v=MCizY0Iw8xY
